---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "act_runner.fullname" . }}-pvc
  labels:
    {{- include "act_runner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1024Mi"
  storageClassName: {{ .Values.act_runner.storageclass }}
