---
{{- $token := .Values.act_runner.token | required ".Values.act_runner.token is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "act_runner.fullname" . }}-secret
  labels:
    {{- include "act_runner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  act-runner-token: {{ .Values.act_runner.token | b64enc }}

